version: '3.8'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: "fruitweb"
      MYSQL_USER: "thongne"
      MYSQL_PASSWORD: "123"
      MYSQL_ROOT_PASSWORD: "123"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./fruitweb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "13306:3306"
  spring-boot:
    image: thonghoang190922/fruitweb-spring-boot:v1.0.0
#    environment:
#      SPRING_DATASOURCE_URL: "jdbc:mariadb://localhost:13306/fruitweb"
#      SPRING_DATASOURCE_USERNAME: "root"
#      SPRING_DATASOURCE_PASSWORD: "123"
    ports:
      - "9999:8080"
    depends_on:
      - mariadb
    build:
      context: "./"
      dockerfile: "Dockerfile"
#    restart: always
volumes:
  mariadb-data:
